name: README Repos List
on:
  workflow_dispatch:
    inputs:
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Run readme-repos-list
        uses: AnandChowdhary/readme-repos-list@v1.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "Octocat in:readme user:ravoian"
          max: 10

            